[workspace]
members = [
    "logging",
]

[workspace.package]
name = "sal-core"
version = "0.0.4"
edition = "2024"

[workspace.dependencies]
log = "^0.4"
env_logger = "^0.11"
#
# Internal dependencies
logging = { path = "./logging" }
testing = { git = "https://github.com/a-givertzman/rust-testing.git", tag = "0.1.2" }
debugging = { git = "https://github.com/a-givertzman/rust-debuging.git", tag = "0.0.1" }
#
# Serde
bincode = "^2.0"
