[workspace]
resolver = "3"

members = [
    "sal-core",
    "sal-core-macros",
]

[workspace.dependencies]
log = "^0.4"
env_logger = "^0.11"
#
# Internal dependencies
testing = { git = "https://github.com/a-givertzman/rust-testing.git", tag = "0.1.2" }
debugging = { git = "https://github.com/a-givertzman/rust-debuging.git", tag = "0.0.1" }
#
# Serde
bincode = "^2.0"
